# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    order.order_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments: [ { createdAt: ~ } ]
        tags: [ 'api_platform.filter' ]

    order.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'order.search' } ]
